# Generated by Django 6.0.2 on 2026-03-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('PR', 'Preparing'), ('D', 'Delivered')], default='P', max_length=2),
        ),
    ]
