# Generated by Django 6.0.2 on 2026-03-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='available_toppings',
            field=models.ManyToManyField(blank=True, to='orders.topping'),
        ),
    ]
