# Generated by Django 5.2.12 on 2026-04-16 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Side',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('side_type', models.CharField(choices=[('nuggets', 'Chicken Nuggets'), ('mozzarella', 'Mozzarella Sticks'), ('churros', 'Churros'), ('chilli', 'Chilli Poppers'), ('dip', 'Dip Sauce')], default='dip', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='allergens',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pizza',
            name='category',
            field=models.CharField(choices=[('bestseller', 'Best Seller'), ('discount', 'Discount'), ('classic', 'Classic'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan')], default='classic', max_length=20),
        ),
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pizzas/'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pizza',
            name='is_vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pizza',
            name='is_vegetarian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='side',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.side'),
        ),
    ]
